import React from 'react';
import { Download } from 'lucide-react';

const DownloadSummaryButton = ({ analysis }) => {
  const handleDownload = () => {
    if (!analysis) return;

    const content = `
Medical Report Analysis Summary
================================

Risk Level: ${analysis.riskLevel || 'N/A'}
Risk Score: ${analysis.riskScore ?? 'N/A'}/100

Summary:
--------
${analysis.summary || 'No summary available'}

Generated by AI Medical Report Analyzer
Date: ${new Date().toLocaleString()}
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `medical-report-summary-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleDownload}
      className="inline-flex items-center gap-2 px-4 py-2.5 bg-white hover:bg-gray-50 text-gray-700 rounded-full font-medium transition-all duration-200 border border-gray-200 shadow-sm text-sm"
    >
      <Download className="w-4 h-4 text-blue-500" />
      <span className="hidden sm:inline-block">Download</span>
    </button>
  );
};

export default DownloadSummaryButton;
