import React from 'react';
import jsPDF from 'jspdf';

const DownloadSummaryButton = ({ analysis }) => {
  const handleDownload = () => {
    if (!analysis) return;

    const doc = new jsPDF();
    let y = 10;

    // Header band
    doc.setFillColor(11, 94, 215);
    doc.rect(0, 0, 210, 24, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text('AI Medical Report Summary', 10, 15);
    doc.setFontSize(10);
    doc.text('Generated by AI Medical Report Analyzer', 10, 21);
    doc.setTextColor(0, 0, 0);
    y = 32;

    doc.setFontSize(11);
    if (analysis.reportType || analysis.date) {
      doc.setFontSize(10);
      doc.setTextColor(80, 80, 80);
      doc.text(`Report: ${analysis.reportType || 'Unknown'}   Date: ${analysis.date || 'Unknown'}`, 10, y);
      doc.setTextColor(0, 0, 0);
      y += 8;
    }

    doc.text(`Overall Risk Score: ${analysis.riskScore}/100`, 10, y);
    y += 6;
    doc.text(`Risk Level: ${analysis.riskLevel}`, 10, y);
    y += 8;

    // Simple risk bar
    const score = Math.max(0, Math.min(100, Number(analysis.riskScore || 0)));
    const barW = 160;
    const barH = 6;
    doc.setFillColor(233, 236, 239);
    doc.rect(10, y, barW, barH, 'F');
    const color = score >= 70 ? [220, 53, 69] : score >= 40 ? [255, 193, 7] : [25, 135, 84];
    doc.setFillColor(color[0], color[1], color[2]);
    doc.rect(10, y, (barW * score) / 100, barH, 'F');
    y += 12;

    doc.setFontSize(12);
    doc.text('Summary', 10, y);
    y += 6;
    doc.setFontSize(10);
    const summaryLines = doc.splitTextToSize(analysis.summary || '', 190);
    doc.text(summaryLines, 10, y);
    y += summaryLines.length * 5 + 4;

    if (analysis.metrics && analysis.metrics.length > 0) {
      doc.setFontSize(12);
      doc.text('Indicators / Parameters', 10, y);
      y += 6;
      doc.setFontSize(10);
      analysis.metrics.forEach((m) => {
        if (y > 280) {
          doc.addPage();
          y = 10;
        }
        const line = `${m.label}: ${m.value} ${m.unit} (${m.status})`;
        doc.text(line, 10, y);
        y += 5;
      });
      y += 4;
    }

    // Simple mini bar chart for indicators (0-100)
    if (analysis.metrics && analysis.metrics.length > 0) {
      doc.setFontSize(12);
      doc.text('Chart (0–100)', 10, y);
      y += 6;
      const top = y;
      const maxBars = Math.min(6, analysis.metrics.length);
      for (let i = 0; i < maxBars; i++) {
        const m = analysis.metrics[i];
        const v = Math.max(0, Math.min(100, Number(m.value || 0)));
        const rowY = top + i * 8;
        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        doc.text((m.label || '').slice(0, 18), 10, rowY);
        doc.setTextColor(0, 0, 0);
        doc.setFillColor(233, 236, 239);
        doc.rect(55, rowY - 4, 120, 5, 'F');
        const c = m.color === 'red' ? [220, 53, 69] : m.color === 'yellow' ? [255, 193, 7] : [25, 135, 84];
        doc.setFillColor(c[0], c[1], c[2]);
        doc.rect(55, rowY - 4, (120 * v) / 100, 5, 'F');
      }
      y = top + maxBars * 8 + 6;
    }

    if (analysis.dietAndLifestyle && analysis.dietAndLifestyle.length > 0) {
      doc.setFontSize(12);
      doc.text('Diet & Lifestyle Suggestions', 10, y);
      y += 6;
      doc.setFontSize(10);
      analysis.dietAndLifestyle.forEach((item) => {
        const lines = doc.splitTextToSize(`• ${item}`, 190);
        if (y > 280) {
          doc.addPage();
          y = 10;
        }
        doc.text(lines, 10, y);
        y += lines.length * 5;
      });
      y += 4;
    }

    if (analysis.doctorRecommendation) {
      doc.setFontSize(12);
      doc.text('Doctor Recommendation', 10, y);
      y += 6;
      doc.setFontSize(10);
      const recLines = doc.splitTextToSize(analysis.doctorRecommendation, 190);
      doc.text(recLines, 10, y);
    }

    doc.save('health-summary.pdf');
  };

  return (
    <button
      type="button"
      className="btn btn-sm btn-outline-primary"
      onClick={handleDownload}
      disabled={!analysis}
    >
      <i className="bi bi-download me-1"></i>
      Download Summary
    </button>
  );
};

export default DownloadSummaryButton;

