import React, { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../services/AuthContext';
import { database, dbRef, onValue, remove as fbRemove } from '../services/firebaseClient';
import DownloadSummaryButton from '../components/DownloadSummaryButton';
import { SkeletonCard } from '../components/Skeleton';
import {
  FolderOpen,
  Search,
  Upload,
  Eye,
  Share2,
  Trash2,
  Calendar,
  AlertCircle,
  CheckCircle,
  Clock,
  Inbox,
  Copy,
  Mail
} from 'lucide-react';

function formatDate(ts) {
  try {
    if (!ts) return 'Unknown date';
    const date = new Date(ts);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;

    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch {
    return 'Unknown date';
  }
}

const getRiskBadgeStyles = (score) => {
  if (score >= 70) {
    return 'bg-gradient-to-r from-red-500 to-rose-500 text-white shadow-lg shadow-red-200';
  }
  if (score >= 40) {
    return 'bg-gradient-to-r from-amber-400 to-orange-400 text-white shadow-lg shadow-amber-200';
  }
  return 'bg-gradient-to-r from-emerald-500 to-teal-500 text-white shadow-lg shadow-emerald-200';
};

const getRiskIcon = (score) => {
  if (score >= 70) return <AlertCircle className="w-4 h-4" />;
  if (score >= 40) return <Clock className="w-4 h-4" />;
  return <CheckCircle className="w-4 h-4" />;
};

const ReportsPage = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');

  useEffect(() => {
    if (!user) return;
    setLoading(true);
    const reportsRef = dbRef(database, `users/${user.uid}/reports`);
    const unsub = onValue(reportsRef, (snapshot) => {
      const val = snapshot.val() || {};
      const list = Object.entries(val)
        .map(([id, data]) => ({ id, ...data }))
        .sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0));
      setReports(list);
      setLoading(false);
    });
    return () => unsub();
  }, [user]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return reports;
    return reports.filter((r) => {
      const name = (r.fileName || '').toLowerCase();
      const summary = (r.analysis?.summary || '').toLowerCase();
      const risk = (r.analysis?.riskLevel || '').toLowerCase();
      return name.includes(q) || summary.includes(q) || risk.includes(q);
    });
  }, [reports, query]);

  const handleDelete = async (reportId) => {
    if (!user) return;
    if (!confirm('Delete this report from history?')) return;
    await fbRemove(dbRef(database, `users/${user.uid}/reports/${reportId}`));
  };

  const handleShare = async (report) => {
    const text =
      `AI Medical Report Analysis\n\n` +
      `Report: ${report.fileName || report.id}\n` +
      `Risk: ${report.analysis?.riskLevel || 'N/A'} (${report.analysis?.riskScore ?? 'N/A'}/100)\n\n` +
      `Summary:\n${report.analysis?.summary || 'No summary available'}`;

    try {
      await navigator.clipboard.writeText(text);
      alert('✓ Summary copied to clipboard');
    } catch {
      alert('Could not copy automatically');
    }
  };

  const handleWhatsapp = (report) => {
    const msg =
      `📋 Medical Report Analysis\n\n` +
      `Report: ${report.fileName || report.id}\n` +
      `Risk: ${report.analysis?.riskLevel || 'N/A'} (${report.analysis?.riskScore ?? 'N/A'}/100)\n\n` +
      `${report.analysis?.summary || ''}`;
    const url = `https://wa.me/?text=${encodeURIComponent(msg)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const handleEmail = (report) => {
    const subject = `Medical Report: ${report.fileName || report.id}`;
    const body =
      `Medical Report Analysis\n\n` +
      `Risk Level: ${report.analysis?.riskLevel || 'N/A'}\n` +
      `Risk Score: ${report.analysis?.riskScore ?? 'N/A'}/100\n\n` +
      `Summary:\n${report.analysis?.summary || ''}\n\n` +
      `Generated by AI Medical Report Analyzer`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-cyan-50">
      {/* Header Section */}
      <div className="bg-white/80 backdrop-blur-lg border-b border-gray-100 sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex flex-col lg:flex-row justify-between items-start gap-6">
            <div className="flex-1">
              <div className="flex items-center gap-4 mb-3">
                <div className="p-4 bg-gradient-to-br from-blue-500 via-blue-600 to-cyan-500 rounded-2xl shadow-xl shadow-blue-200/50 transform hover:scale-105 transition-all duration-300">
                  <FolderOpen className="w-8 h-8 text-white" />
                </div>
                <div>
                  <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 via-cyan-600 to-teal-600 bg-clip-text text-transparent">
                    Report History
                  </h1>
                  <div className="flex items-center gap-3 mt-2">
                    <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-blue-100 text-blue-700">
                      {reports.length} {reports.length === 1 ? 'Report' : 'Reports'}
                    </span>
                    <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-green-100 text-green-700">
                      {filtered.length} {filtered.length === 1 ? 'Result' : 'Results'}
                    </span>
                  </div>
                </div>
              </div>
              <p className="text-gray-600 text-lg max-w-2xl">
                Manage and share your AI-powered medical report analyses
              </p>
            </div>

            <div className="flex flex-col sm:flex-row gap-4 w-full lg:w-auto">
              <div className="relative flex-1 sm:flex-initial">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="text"
                  className="w-full sm:w-96 pl-12 pr-4 py-3.5 bg-gray-50/50 border border-gray-200 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all duration-300 text-gray-700 placeholder-gray-400"
                  placeholder="Search reports by name, risk level, or summary..."
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                />
                {query && (
                  <button
                    onClick={() => setQuery('')}
                    className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                  >
                    ×
                  </button>
                )}
              </div>
              <Link
                to="/dashboard"
                className="inline-flex items-center justify-center gap-3 px-8 py-3.5 bg-gradient-to-r from-blue-600 via-cyan-600 to-teal-600 hover:from-blue-700 hover:via-cyan-700 hover:to-teal-700 text-white rounded-2xl font-bold transition-all duration-300 shadow-lg shadow-blue-200/50 hover:shadow-xl hover:shadow-blue-300/70 transform hover:-translate-y-0.5"
              >
                <Upload className="w-5 h-5" />
                <span>New Analysis</span>
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {Array.from({ length: 6 }).map((_, i) => (
              <SkeletonCard key={i} />
            ))}
          </div>
        ) : filtered.length === 0 ? (
          <div className="bg-white/60 backdrop-blur-sm rounded-3xl p-16 text-center shadow-xl border border-gray-100">
            <div className="max-w-md mx-auto">
              <div className="w-24 h-24 bg-gradient-to-br from-gray-100 to-gray-50 rounded-full flex items-center justify-center mx-auto mb-8 shadow-inner">
                <Inbox className="w-12 h-12 text-gray-400" />
              </div>
              <h3 className="text-3xl font-bold text-gray-800 mb-4">
                {query ? 'No Reports Found' : 'No Reports Yet'}
              </h3>
              <p className="text-gray-500 text-lg mb-8">
                {query
                  ? 'Try adjusting your search terms or browse all reports'
                  : 'Upload your first medical report to start building your health history'}
              </p>
              {!query && (
                <Link
                  to="/dashboard"
                  className="inline-flex items-center gap-3 px-8 py-4 bg-gradient-to-r from-blue-600 via-cyan-600 to-teal-600 hover:from-blue-700 hover:via-cyan-700 hover:to-teal-700 text-white rounded-2xl font-bold transition-all duration-300 shadow-lg shadow-blue-200/50 hover:shadow-xl hover:shadow-blue-300/70 transform hover:-translate-y-0.5"
                >
                  <Upload className="w-6 h-6" />
                  <span>Upload First Report</span>
                </Link>
              )}
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {filtered.map((r, index) => (
              <div
                key={r.id}
                className="group bg-white/80 backdrop-blur-sm rounded-3xl p-6 shadow-lg border border-gray-100 hover:shadow-2xl hover:-translate-y-2 transition-all duration-500 flex flex-col relative overflow-hidden"
                style={{ animationDelay: `${index * 100}ms` }}
              >
                {/* Gradient overlay on hover */}
                <div className="absolute inset-0 bg-gradient-to-br from-blue-500/5 via-transparent to-cyan-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                
                {/* Header */}
                <div className="flex justify-between items-start gap-4 mb-6 relative z-10">
                  <div className="flex-1 min-w-0">
                    <h3 className="font-bold text-gray-800 truncate text-xl mb-3 group-hover:text-blue-600 transition-colors">
                      {r.fileName || 'Medical Report'}
                    </h3>
                    <div className="flex items-center gap-2 text-sm text-gray-500">
                      <Calendar className="w-4 h-4" />
                      <span>{formatDate(r.createdAt)}</span>
                    </div>
                  </div>
                  <div className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-bold whitespace-nowrap shadow-lg ${getRiskBadgeStyles(r.analysis?.riskScore || 0)}`}>
                    {getRiskIcon(r.analysis?.riskScore || 0)}
                    <span>{r.analysis?.riskScore ?? 'N/A'}</span>
                  </div>
                </div>

                {/* Summary Section */}
                <div className="bg-gradient-to-br from-gray-50/80 via-blue-50/50 to-cyan-50/30 rounded-2xl p-5 mb-6 flex-1 relative z-10">
                  <div className="flex items-center gap-2 mb-3">
                    <div className="w-2 h-2 bg-blue-500 rounded-full" />
                    <p className="text-xs text-gray-500 font-bold uppercase tracking-wider">AI Summary</p>
                  </div>
                  <p className="text-sm text-gray-700 line-clamp-4 leading-relaxed">
                    {r.analysis?.summary || 'No summary available'}
                  </p>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-wrap gap-3 pt-6 border-t border-gray-100 relative z-10">
                  <button
                    onClick={() => navigate(`/report/${encodeURIComponent(r.id)}`)}
                    className="inline-flex items-center gap-2 px-5 py-3 bg-gradient-to-r from-blue-600 via-cyan-600 to-teal-600 hover:from-blue-700 hover:via-cyan-700 hover:to-teal-700 text-white rounded-xl font-bold transition-all duration-300 shadow-lg shadow-blue-200/50 hover:shadow-xl hover:shadow-blue-300/70 transform hover:-translate-y-0.5 text-sm"
                  >
                    <Eye className="w-4 h-4" />
                    <span>View Report</span>
                  </button>

                  <DownloadSummaryButton analysis={r.analysis} />

                  <div className="relative group">
                    <button className="inline-flex items-center gap-2 px-5 py-3 bg-white hover:bg-gray-50 text-gray-700 rounded-xl font-bold transition-all duration-300 border border-gray-200 shadow-sm hover:shadow-md text-sm">
                      <Share2 className="w-4 h-4" />
                      <span>Share</span>
                    </button>
                    <div className="absolute bottom-full left-0 mb-2 hidden group-hover:block bg-white rounded-2xl shadow-2xl border border-gray-200 py-3 min-w-[180px] z-20">
                      <button
                        onClick={() => handleShare(r)}
                        className="w-full flex items-center gap-3 px-4 py-3 hover:bg-blue-50 text-gray-700 text-sm transition-colors rounded-xl"
                      >
                        <Copy className="w-4 h-4" />
                        <span>Copy Text</span>
                      </button>
                      <button
                        onClick={() => handleWhatsapp(r)}
                        className="w-full flex items-center gap-3 px-4 py-3 hover:bg-green-50 text-gray-700 text-sm transition-colors rounded-xl"
                      >
                        <Share2 className="w-4 h-4" />
                        <span>WhatsApp</span>
                      </button>
                      <button
                        onClick={() => handleEmail(r)}
                        className="w-full flex items-center gap-3 px-4 py-3 hover:bg-blue-50 text-gray-700 text-sm transition-colors rounded-xl"
                      >
                        <Mail className="w-4 h-4" />
                        <span>Email</span>
                      </button>
                    </div>
                  </div>

                  <button
                    onClick={() => handleDelete(r.id)}
                    className="inline-flex items-center gap-2 px-5 py-3 bg-white hover:bg-red-50 text-red-600 rounded-xl font-bold transition-all duration-300 border border-red-200 shadow-sm hover:shadow-md text-sm ml-auto"
                  >
                    <Trash2 className="w-4 h-4" />
                    <span>Delete</span>
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default ReportsPage;
