import React, { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../services/AuthContext';
import { database, dbRef, onValue, remove as fbRemove } from '../services/firebaseClient';
import DownloadSummaryButton from '../components/DownloadSummaryButton';
import { SkeletonCard } from '../components/Skeleton';

function formatDate(ts) {
  try {
    if (!ts) return 'Unknown date';
    return new Date(ts).toLocaleString();
  } catch {
    return 'Unknown date';
  }
}

const ReportsPage = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');

  useEffect(() => {
    if (!user) return;
    setLoading(true);
    const reportsRef = dbRef(database, `users/${user.uid}/reports`);
    const unsub = onValue(reportsRef, (snapshot) => {
      const val = snapshot.val() || {};
      const list = Object.entries(val)
        .map(([id, data]) => ({ id, ...data }))
        .sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0));
      setReports(list);
      setLoading(false);
    });
    return () => unsub();
  }, [user]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return reports;
    return reports.filter((r) => {
      const name = (r.fileName || '').toLowerCase();
      const summary = (r.analysis?.summary || '').toLowerCase();
      const risk = (r.analysis?.riskLevel || '').toLowerCase();
      return name.includes(q) || summary.includes(q) || risk.includes(q);
    });
  }, [reports, query]);

  const handleDelete = async (reportId) => {
    if (!user) return;
    const ok = confirm('Delete this report from history?');
    if (!ok) return;
    await fbRemove(dbRef(database, `users/${user.uid}/reports/${reportId}`));
  };

  const handleShare = async (report) => {
    const text =
      `AI Medical Report Analyzer\n` +
      `Report: ${report.fileName || report.id}\n` +
      `Risk: ${report.analysis?.riskLevel || 'N/A'} (${report.analysis?.riskScore ?? 'N/A'}/100)\n` +
      `Summary: ${report.analysis?.summary || ''}`.slice(0, 900);

    // Copy to clipboard
    try {
      await navigator.clipboard.writeText(text);
      alert('Copied share text to clipboard.');
    } catch {
      alert('Could not copy automatically. You can manually copy from the next dialog.');
      prompt('Copy this text:', text);
    }
  };

  const handleWhatsapp = (report) => {
    const msg =
      `Report: ${report.fileName || report.id}\n` +
      `Risk: ${report.analysis?.riskLevel || 'N/A'} (${report.analysis?.riskScore ?? 'N/A'}/100)\n` +
      `Summary: ${report.analysis?.summary || ''}`;
    const url = `https://wa.me/?text=${encodeURIComponent(msg)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const handleEmail = (report) => {
    const subject = `Medical report summary: ${report.fileName || report.id}`;
    const body =
      `Risk: ${report.analysis?.riskLevel || 'N/A'} (${report.analysis?.riskScore ?? 'N/A'}/100)\n\n` +
      `Summary:\n${report.analysis?.summary || ''}\n\n` +
      `Generated by AI Medical Report Analyzer.`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  return (
    <div className="container-fluid py-4 fade-in">
      <div className="row g-4 mb-4">
        <div className="col-12">
          <div className="card-modern p-4 bg-white border-0 shadow-lg">
            <div className="d-flex flex-column flex-md-row justify-content-between align-items-start gap-3">
              <div>
                <div className="d-flex align-items-center mb-2">
                  <div className="rounded-circle bg-primary bg-opacity-10 p-2 me-2">
                    <i className="bi bi-folder2-open text-primary fs-5"></i>
                  </div>
                  <h2 className="fw-bold mb-0">Report History</h2>
                </div>
                <p className="text-muted mb-0">
                  View, share, download, or manage your previously analyzed medical reports.
                </p>
              </div>
              <div className="d-flex gap-2 w-100 w-md-auto">
                <div className="input-group" style={{maxWidth: '300px'}}>
                  <span className="input-group-text bg-light border-0">
                    <i className="bi bi-search text-muted"></i>
                  </span>
                  <input
                    className="form-control border-0 bg-light"
                    placeholder="Search reports..."
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                  />
                </div>
                <Link to="/dashboard" className="btn btn-primary btn-glow rounded-pill px-4 py-2 text-decoration-none">
                  <i className="bi bi-cloud-arrow-up me-2"></i>
                  New Analysis
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>

      {loading ? (
        <div className="row g-4">
          {Array.from({ length: 6 }).map((_, i) => (
            <div className="col-12 col-md-6 col-lg-4" key={i}>
              <SkeletonCard />
            </div>
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <div className="row">
          <div className="col-12">
            <div className="card-modern p-5 bg-white text-center border-0 shadow-lg">
              <div className="rounded-circle bg-primary bg-opacity-10 p-4 mx-auto mb-3" style={{width: '80px', height: '80px'}}>
                <i className="bi bi-inbox text-primary" style={{fontSize: '2.5rem'}}></i>
              </div>
              <h4 className="fw-bold mb-2">No Reports Found</h4>
              <p className="text-muted mb-4">
                {query ? 'Try adjusting your search terms.' : 'Upload your first medical report to start building your health history.'}
              </p>
              {!query && (
                <Link to="/dashboard" className="btn btn-primary btn-glow rounded-pill px-4 py-2 text-decoration-none">
                  <i className="bi bi-cloud-arrow-up me-2"></i>
                  Upload First Report
                </Link>
              )}
            </div>
          </div>
        </div>
      ) : (
        <div className="row g-4">
          {filtered.map((r) => (
            <div className="col-12 col-md-6 col-lg-4" key={r.id}>
              <div className="card-modern p-4 bg-white hover-lift h-100 border-0 shadow-lg">
                <div className="d-flex justify-content-between align-items-start gap-3 mb-3">
                  <div className="flex-grow-1">
                    <h6 className="fw-bold mb-1 text-truncate">{r.fileName || 'Medical Report'}</h6>
                    <div className="small text-muted">
                      <i className="bi bi-calendar3 me-1"></i>
                      {formatDate(r.createdAt)}
                    </div>
                  </div>
                  <span className={`badge rounded-pill ${
                    (r.analysis?.riskScore || 0) >= 70
                      ? 'bg-danger'
                      : (r.analysis?.riskScore || 0) >= 40
                        ? 'bg-warning'
                        : 'bg-success'
                  }`}>
                    {r.analysis?.riskScore ?? 'N/A'}/100
                  </span>
                </div>

                <div className="mb-3">
                  <div className="small text-muted mb-2">Summary:</div>
                  <div className="small" style={{minHeight: '60px'}}>
                    {(r.analysis?.summary || 'No summary available.').slice(0, 120)}
                    {(r.analysis?.summary || '').length > 120 ? '…' : ''}
                  </div>
                </div>

                <div className="d-flex flex-wrap gap-2 mt-auto">
                  <button
                    className="btn btn-primary btn-sm rounded-pill"
                    onClick={() => navigate(`/dashboard?reportId=${encodeURIComponent(r.id)}`)}
                  >
                    <i className="bi bi-eye me-1"></i>
                    View
                  </button>
                  <DownloadSummaryButton analysis={r.analysis} />
                  <div className="dropdown">
                    <button
                      className="btn btn-outline-secondary btn-sm rounded-pill dropdown-toggle"
                      type="button"
                      data-bs-toggle="dropdown"
                    >
                      <i className="bi bi-share me-1"></i>
                      Share
                    </button>
                    <ul className="dropdown-menu">
                      <li><button className="dropdown-item" onClick={() => handleShare(r)}>
                        <i className="bi bi-clipboard me-2"></i>Copy Link
                      </button></li>
                      <li><button className="dropdown-item" onClick={() => handleWhatsapp(r)}>
                        <i className="bi bi-whatsapp me-2"></i>WhatsApp
                      </button></li>
                      <li><button className="dropdown-item" onClick={() => handleEmail(r)}>
                        <i className="bi bi-envelope me-2"></i>Email
                      </button></li>
                    </ul>
                  </div>
                  <button 
                    className="btn btn-outline-danger btn-sm rounded-pill" 
                    onClick={() => handleDelete(r.id)}
                  >
                    <i className="bi bi-trash me-1"></i>
                    Delete
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default ReportsPage;

