import React, { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../services/AuthContext';
import { database, dbRef, onValue, remove as fbRemove } from '../services/firebaseClient';
import DownloadSummaryButton from '../components/DownloadSummaryButton';
import { SkeletonCard } from '../components/Skeleton';

function formatDate(ts) {
  try {
    if (!ts) return 'Unknown date';
    return new Date(ts).toLocaleString();
  } catch {
    return 'Unknown date';
  }
}

const ReportsPage = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');

  useEffect(() => {
    if (!user) return;
    setLoading(true);
    const reportsRef = dbRef(database, `users/${user.uid}/reports`);
    const unsub = onValue(reportsRef, (snapshot) => {
      const val = snapshot.val() || {};
      const list = Object.entries(val)
        .map(([id, data]) => ({ id, ...data }))
        .sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0));
      setReports(list);
      setLoading(false);
    });
    return () => unsub();
  }, [user]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return reports;
    return reports.filter((r) => {
      const name = (r.fileName || '').toLowerCase();
      const summary = (r.analysis?.summary || '').toLowerCase();
      const risk = (r.analysis?.riskLevel || '').toLowerCase();
      return name.includes(q) || summary.includes(q) || risk.includes(q);
    });
  }, [reports, query]);

  const handleDelete = async (reportId) => {
    if (!user) return;
    const ok = confirm('Delete this report from history?');
    if (!ok) return;
    await fbRemove(dbRef(database, `users/${user.uid}/reports/${reportId}`));
  };

  const handleShare = async (report) => {
    const text =
      `AI Medical Report Analyzer\n` +
      `Report: ${report.fileName || report.id}\n` +
      `Risk: ${report.analysis?.riskLevel || 'N/A'} (${report.analysis?.riskScore ?? 'N/A'}/100)\n` +
      `Summary: ${report.analysis?.summary || ''}`.slice(0, 900);

    // Copy to clipboard
    try {
      await navigator.clipboard.writeText(text);
      alert('Copied share text to clipboard.');
    } catch {
      alert('Could not copy automatically. You can manually copy from the next dialog.');
      prompt('Copy this text:', text);
    }
  };

  const handleWhatsapp = (report) => {
    const msg =
      `Report: ${report.fileName || report.id}\n` +
      `Risk: ${report.analysis?.riskLevel || 'N/A'} (${report.analysis?.riskScore ?? 'N/A'}/100)\n` +
      `Summary: ${report.analysis?.summary || ''}`;
    const url = `https://wa.me/?text=${encodeURIComponent(msg)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const handleEmail = (report) => {
    const subject = `Medical report summary: ${report.fileName || report.id}`;
    const body =
      `Risk: ${report.analysis?.riskLevel || 'N/A'} (${report.analysis?.riskScore ?? 'N/A'}/100)\n\n` +
      `Summary:\n${report.analysis?.summary || ''}\n\n` +
      `Generated by AI Medical Report Analyzer.`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  return (
    <div className="container py-4 fade-in">
      <div className="d-flex flex-column flex-md-row justify-content-between align-items-start gap-2 mb-3">
        <div>
          <h2 className="h4 fw-bold mb-1">
            <i className="bi bi-folder2-open me-2 text-primary"></i>
            Report History
          </h2>
          <div className="text-muted small">
            View, share, download, or delete your previously analyzed reports.
          </div>
        </div>
        <div className="d-flex gap-2 w-100 w-md-auto">
          <input
            className="form-control"
            placeholder="Search reports..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
          <Link to="/dashboard" className="btn btn-primary btn-glow">
            <i className="bi bi-cloud-arrow-up me-2"></i>
            New analysis
          </Link>
        </div>
      </div>

      {loading ? (
        <div className="row g-3">
          {Array.from({ length: 6 }).map((_, i) => (
            <div className="col-12 col-md-6 col-lg-4" key={i}>
              <SkeletonCard />
            </div>
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <div className="card-modern p-4 bg-white text-center">
          <i className="bi bi-inbox fs-1 text-secondary"></i>
          <div className="fw-semibold mt-2">No reports found</div>
          <div className="text-muted small">Upload a report to start building history.</div>
        </div>
      ) : (
        <div className="row g-3">
          {filtered.map((r) => (
            <div className="col-12 col-md-6 col-lg-4" key={r.id}>
              <div className="card-modern p-4 bg-white hover-lift h-100 d-flex flex-column">
                <div className="d-flex justify-content-between align-items-start gap-2">
                  <div className="text-truncate">
                    <div className="fw-semibold text-truncate">{r.fileName || 'Report'}</div>
                    <div className="small text-muted">{formatDate(r.createdAt)}</div>
                  </div>
                  <span
                    className={`badge ${
                      (r.analysis?.riskScore || 0) >= 70
                        ? 'text-bg-danger'
                        : (r.analysis?.riskScore || 0) >= 40
                        ? 'text-bg-warning'
                        : 'text-bg-success'
                    }`}
                  >
                    {r.analysis?.riskScore ?? 'N/A'}/100
                  </span>
                </div>

                <div className="small text-muted mt-3" style={{ minHeight: 54 }}>
                  {(r.analysis?.summary || 'No summary available.').slice(0, 140)}
                  {(r.analysis?.summary || '').length > 140 ? '…' : ''}
                </div>

                <div className="mt-auto pt-3 d-flex flex-wrap gap-2">
                  <button
                    className="btn btn-outline-primary btn-sm"
                    onClick={() => navigate(`/dashboard?reportId=${encodeURIComponent(r.id)}`)}
                  >
                    <i className="bi bi-eye me-1"></i>
                    View
                  </button>
                  <DownloadSummaryButton analysis={r.analysis} />
                  <button className="btn btn-outline-secondary btn-sm" onClick={() => handleShare(r)}>
                    <i className="bi bi-share me-1"></i>
                    Share
                  </button>
                  <button className="btn btn-outline-success btn-sm" onClick={() => handleWhatsapp(r)}>
                    <i className="bi bi-whatsapp me-1"></i>
                    WhatsApp
                  </button>
                  <button className="btn btn-outline-dark btn-sm" onClick={() => handleEmail(r)}>
                    <i className="bi bi-envelope me-1"></i>
                    Email
                  </button>
                  <button className="btn btn-outline-danger btn-sm" onClick={() => handleDelete(r.id)}>
                    <i className="bi bi-trash me-1"></i>
                    Delete
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default ReportsPage;

